import type { Lead } from "./coach";

export const demoLeads: Lead[] = [
  {
    name: "Priya Mehta",
    stage: "warm",
    context: "Needs a 3-bedroom home with the main bedroom on the ground floor. Budget is flexible after bank pre-approval.",
    reason: "You promised to check her financing progress before widening the search area.",
    nextAction: "Ask whether the bank confirmed her pre-approved amount.",
    due: "Today",
    daysQuiet: 8,
    workstream: "warm_nurture",
    channel: "WhatsApp",
  },
  {
    name: "Arjun Rao",
    stage: "hot",
    context: "Visited two family homes in Fremont. His partner preferred the quieter street near Mission schools.",
    reason: "He viewed both homes yesterday and has not shared which trade-off matters most.",
    nextAction: "Call and ask which concern is stopping a second visit.",
    due: "Today",
    daysQuiet: 1,
    workstream: "active_opportunity",
    channel: "Call",
  },
  {
    name: "Neha Kapoor",
    stage: "nurture",
    context: "Relocating for work in November. Wants a rental first, then plans to buy after learning the area.",
    reason: "Her relocation date is now close enough to restart the rental search.",
    nextAction: "Send three rental options and offer a 15-minute area call.",
    due: "This afternoon",
    daysQuiet: 34,
    workstream: "warm_nurture",
    channel: "Email",
  },
  {
    name: "Rohan Shah",
    stage: "waiting",
    context: "Interested in new-build homes but will not move before his current lease ends.",
    reason: "His lease-end date is still unknown.",
    nextAction: "Ask when his current lease ends before scheduling another search.",
    due: "This week",
    daysQuiet: 15,
    workstream: "overdue",
    channel: "Call",
  },
  {
    name: "Maya Singh",
    stage: "warm",
    context: "Downloaded the first-time buyer guide after seeing your neighborhood advertisement.",
    reason: "She is a new inbound lead and has not yet received a personal response.",
    nextAction: "Introduce yourself and ask what prompted her home search.",
    due: "Before noon",
    daysQuiet: 0,
    workstream: "new_outreach",
    channel: "WhatsApp",
  },
  {
    name: "Daniel Kim",
    stage: "nurture",
    context: "Met at an open house six months ago. Interested in investment property after his annual bonus.",
    reason: "His expected bonus month begins next week.",
    nextAction: "Reconnect with one relevant investment option and a simple yield comparison.",
    due: "Today",
    daysQuiet: 61,
    workstream: "warm_nurture",
    channel: "Email",
  },
  {
    name: "Anita Desai",
    stage: "hot",
    context: "Selling her current condo before buying. She asked for a pricing opinion after the weekend showing.",
    reason: "A pricing decision is blocking both the listing and her next purchase.",
    nextAction: "Call with the three comparable sales and agree on a listing-price range.",
    due: "10:30 AM",
    daysQuiet: 2,
    workstream: "active_opportunity",
    channel: "Call",
  },
  {
    name: "Omar Ali",
    stage: "waiting",
    context: "Requested a relocation-area comparison and said he would review it with his family.",
    reason: "The promised check-in was due yesterday and no outcome was recorded.",
    nextAction: "Ask which area the family preferred and what remains unclear.",
    due: "Overdue by 1 day",
    daysQuiet: 9,
    workstream: "overdue",
    channel: "WhatsApp",
  },
];
